export const SHOW_LOADER = 'SHOW_LOADER'
export const ADD_TO_CART = 'ADD_TO_CART'
export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS'
export const FETCH_ALL_PRODUCTS = 'FETCH_CART_PRODUCTS'

// export const CHANGE_QTY_CART_PRODUCT = ""
export const FETCH_CATS = 'FETCH_CATS'
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'
export const LOGOUT = 'LOGOUT'
